name: usecase
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  domain:
    path: ../../core/domain/
  riverpod: ^2.4.8
  riverpod_annotation: ^2.3.2
  value:
    path: ../../core/value/

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.7
  riverpod_generator: ^2.3.8
  riverpod_lint: ^2.3.6
  source_gen: ^1.5.0
  test: ^1.24.0
  very_good_analysis: ^5.1.0
