name: value
description: "A new Flutter plugin project."
version: 0.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  riverpod_annotation: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
