name: octopus_viewer
description: "OctopusEnergy's electric usage viewer."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: 3.16.0

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.8
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  riverpod_annotation: ^2.3.2
  ui:
    path: ../core/ui/

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  custom_lint: ^0.5.7
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.4
  riverpod_generator: ^2.3.8
  riverpod_lint: ^2.3.6
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  