name: Lint and Test the source code
on:
  pull_request:
    branches: [ main ]

jobs:
  Lint-and-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ vars.FLUTTER_SDK_VERSION }}

      - name: Setup Melos
        uses: bluefireteam/melos-action@v3
        with:
          melos-version: ${{ vars.MELOS_VERSION }}

      - name: Run Lint
        run: melos run lint

      - name: Run Test
        run: melos run test
